version: '3.9'

services:
  tfe_dedicated_server:
    image: enda2020/tfe_server
    container_name: tfe_server
    restart: unless-stopped
    network_mode: "host"
    tty: true
    volumes:
      - ./tfe-data:/home/tfe/tfe-dedicated/ 
